### ISSUE TITLE
Mocks.cls using deprecated mockNonVoidMethod & mockVoidMethod method

### ISSUE THREAD

**Issue by JAertgeerts** [financialforcedev/fflib-apex-common-samplecode#11]
Mocks: line 18, column 31: Method does not exist or incorrect signature: [fflib_ApexMocks].mockNonVoidMethod(Mocks.OpportunitiesSelector, String, List)

Needs updating to the more recent version of the [fflib_ApexMocks](https://github.com/financialforcedev/fflib-apex-mocks/blob/master/src/classes/fflib_ApexMocks.cls#L229):
requiring following parameters:
`public Object mockNonVoidMethod(Object mockInstance, String methodName, List<Type> methodArgTypes, List<Object> methodArgValues)`
- @param mockInstance The mock object instance.
- @param methodName The method for which to prepare a return value.
- @param methodArgTypes The method argument types for which to prepare a return value.
- @param methodArgValues The method argument values for which to prepare a return value.

While only receiving the deprecated version:
`public Object mockNonVoidMethod(Object mockInstance, String methodName, Object methodArg)`

- @param mockInstance The mock object instance.
- @param methodName The method for which to prepare a return value.
- @param methodArg The method argument for which to prepare a return value.

This is also causing the deployment of this repository to fail.

**Comment by JAertgeerts** [comment]
Extended to include deprecated mockVoidMethod

**Comment by afawcett** [comment]
THanks, merged! 👍
