### ISSUE TITLE
Error Message "Dependent class is invalid and needs recompilation" when deploying in blank org

### ISSUE THREAD

**Issue by jlraes** [financialforcedev/fflib-apex-common-samplecode#15]
The fflib framework is installed, but when I try to install the sample app, I get the following error message:

Deployment Complete
Failures:
classes/Accounts.cls(53,5):Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/AccountsSelector.cls(53,5):Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/Application.cls(53,5):Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunitiesServiceTestIntegration.cls(53,5):Dependent class is invalid and needs recompilation:
 Class OpportunitiesService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunitiesTest.cls(53,5):Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunitiesServiceTest.cls(53,5):Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunityApplyDiscountController.cls(53,5):Dependent class is invalid and needs recompilation:
 Class OpportunitiesService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunityApplyDiscountControllerTest.cls(53,5):Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunityApplyDiscountControllerTestI.cls(53,5):Dependent class is invalid and needs recompilation:
 Class OpportunityApplyDiscountController : Dependent class is invalid and needs recompilation:
 Class OpportunitiesService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunityConsoleController.cls(53,5):Dependent class is invalid and needs recompilation:
 Class OpportunitiesService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/InvoicingService.cls(53,5):Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/InvoicingServiceImpl.cls(53,5):Dependent class is invalid and needs recompilation:
 Class InvoicingService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/InvoicingServiceTest.cls(53,5):Dependent class is invalid and needs recompilation:
 Class InvoicingService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/Opportunities.cls(53,5):Dependent class is invalid and needs recompilation:
 Class InvoicingService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunitiesResource.cls(53,5):Dependent class is invalid and needs recompilation:
 Class OpportunitiesService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunitiesSelector.cls(53,5):Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunitiesService.cls(53,5):Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunitiesServiceImpl.cls(53,5):Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunityCreateInvoiceController.cls(53,5):Dependent class is invalid and needs recompilation:
 Class OpportunitiesService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunityInvoicingController.cls(53,5):Dependent class is invalid and needs recompilation:
 Class OpportunitiesService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunityLineItems.cls(53,5):Dependent class is invalid and needs recompilation:
 Class Opportunities : Dependent class is invalid and needs recompilation:
 Class InvoicingService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/OpportunityLineItemsSelector.cls(63,22):Method does not exist or incorrect signature: void getFieldListString() from the type OpportunityLineItemsSelector
classes/PricebookEntriesSelector.cls(53,5):Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/CreateInvoicesJob.cls(53,5):Dependent class is invalid and needs recompilation:
 Class OpportunitiesService : Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
classes/DeveloperWorkItemsTest.cls(53,5):Dependent class is invalid and needs recompilation:
 Class Application : Dependent class is invalid and needs recompilation:
 Class OpportunitiesServiceImpl : Dependent class is invalid and needs recompilation:
 Class OpportunitiesSelector : Dependent class is invalid and needs recompilation:
 Class PricebookEntriesSelector : Method does not exist or incorrect signature: void getFieldListString() from the type PricebookEntriesSelector
triggers/OpportunitiesTrigger.trigger(31,37):Invalid type: Opportunities
triggers/OpportunityLineItemsTrigger.trigger(31,37):Invalid type: OpportunityLineItems
pages/opportunityapplydiscount.page(opportunityapplydiscount):Apex class 'OpportunityApplyDiscountController' does not exist
pages/opportunityapplydiscounts.page(opportunityapplydiscounts):Apex class 'OpportunityApplyDiscountController' does not exist
pages/opportunitycreateinvoice.page(opportunitycreateinvoice):Apex class 'OpportunityCreateInvoiceController' does not exist
pages/opportunitycreateinvoices.page(opportunitycreateinvoices):Apex class 'OpportunityCreateInvoiceController' does not exist
pages/opportunityinvoicing.page(opportunityinvoicing):Apex class 'OpportunityInvoicingController' does not exist

**Comment by afawcett** [comment]
This very long deploy log from Salesforce actually stems from one single error...

~~~~
triggers/OpportunitiesTrigger.trigger(31,37):Invalid type: Opportunities
triggers/OpportunityLineItemsTrigger.trigger(31,37):Invalid type: OpportunityLineItems
pages/opportunityapplydiscount.page(opportunityapplydiscount):Apex class 'OpportunityApplyDiscountController' does not exist
pages/opportunityapplydiscounts.page(opportunityapplydiscounts):Apex class 'OpportunityApplyDiscountController' does not exist
pages/opportunitycreateinvoice.page(opportunitycreateinvoice):Apex class 'OpportunityCreateInvoiceController' does not exist
pages/opportunitycreateinvoices.page(opportunitycreateinvoices):Apex class 'OpportunityCreateInvoiceController' does not exist
pages/opportunityinvoicing.page(opportunityinvoicing):Apex class 'OpportunityInvoicingController' does not exist
~~~~

The key bits are this...

~~~~
Invalid type: Opportunities
Invalid type: OpportunityLineItems
~~~~

Are these objects present in your org edition?

Thanks,

Andy

**Comment by jlraes** [comment]
Hi Andy,
No they weren't. Initially I thought in that direction, but I created a new dev org to check.

When I added a function 'getFieldListString' to both OpportunityLineItemsSelector and PricebookEntriesSelector classes, it seemed to deploy the whole package.
Does that make sense ?

Thanks,
Jean-Luc

**Comment by afawcett** [comment]
Hmmm... i think this is a break changing from the recent changes in the core lib... which is not something that should have happened tbh. I'll flag this as a bug. Glad your up and running in the meantime! 👍

**Comment by Ramesh-Peetha** [comment]
Andy,

is this bug fixed, received same error during build. Please help me to get this build successful.

Thanks 
Ramesh

**Comment by afawcett** [comment]
Fixed. Please update your fflib (apex-commons) also.
