### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by jayonsoftware** [financialforcedev/fflib-apex-common-samplecode#16]
I am trying to deploy the sample code to a brand new org (the deployment of mok and common went fine) and i have set the version to 37.0 Getting the following error

C:\apexsharp\AdvanceSalesForce\src\applications\standard__Content.app
Error:(1, 1) Property 'formFactors' not valid in version 37.0
C:\apexsharp\AdvanceSalesForce\src\applications\standard__Community.app
Error:(1, 1) Property 'formFactors' not valid in version 37.0
C:\apexsharp\AdvanceSalesForce\src\applications\standard__LightningSalesConsole.app
Error:(1, 1) Property 'formFactors' not valid in version 37.0
C:\apexsharp\AdvanceSalesForce\src\applications\standard__LightningService.app
Error:(1, 1) Property 'formFactors' not valid in version 37.0
C:\apexsharp\AdvanceSalesForce\src\applications\standard__Marketing.app
Error:(1, 1) Property 'formFactors' not valid in version 37.0
C:\apexsharp\AdvanceSalesForce\src\applications\standard__Service.app
Error:(1, 1) Property 'formFactors' not valid in version 37.0
C:\apexsharp\AdvanceSalesForce\src\applications\standard__ServiceConsole.app
Error:(1, 1) Property 'enableListViewHover' not valid in version 37.0

**Comment by jayonsoftware** [comment]
Also another set of errors when deployment the objects

`C:\apexsharp\AdvanceSalesForce\src\objects\Goal.object
Error:(1, 1) insufficient access rights on cross-reference id
C:\apexsharp\AdvanceSalesForce\src\objects\Idea.object
Error:(1, 1) Duplicate name 'Idea.Ideas_Last_7_Days' specified
C:\apexsharp\AdvanceSalesForce\src\objects\Metric.object
Error:(1, 1) insufficient access rights on cross-reference id`

**Comment by afawcett** [comment]
Hi @jayonsoftware these files are are not part of this repository, so i am not 100% how to help. It does look like the .app file metadata needs to be updated to match that specified in API 37. Suggest you either check the Metadata API Developers Guide in order to update the files or if you do not need them delete them (they appear to be the standard apps you get with a DE org). Hope this helps.
